[package]
name = "adana"
version = "0.13.30"
edition = "2021"
authors = ["Nordine Bittich"]
license = "MIT"
description = "namespaces aliases for command lines & basic scripting language"
homepage = "https://github.com/nbittich/adana"
readme = "README.md"
exclude = [
  "vscode/",
  "dist/",
  ".vscode",
  ".history",
  ".git",
  ".github",
  "static_binaries/",
]

[dependencies]
anyhow = "1.0.71"
bincode = "1.3.3"
dirs = "5.0.1"
log = "0.4.18"
nom = { version = "7.1.3" }
nu-ansi-term = "0.48.0"
rustyline = "11.0.0"
rustyline-derive = "0.8.0"
serde = { version = "1.0.164", features = ['serde_derive', 'rc'] }
serde_json = "1.0.96"
slab_tree = "0.3.2"
strum = { version = "0.24.1", features = ["derive"] }
ctrlc = "3.4.0"
[dependencies.env_logger]
default-features = false
version = "0.10.0"
[dependencies.regex]
version = "1.8.3"
default-features = false
# regex currently requires the standard library, you must re-enable it.
features = ["std"]

[profile.release]
opt-level = 'z'   # Optimize for size.
lto = true        # Link Time Optimization (LTO)
codegen-units = 1 # Set this to 1 to allow for maximum size reduction optimizations:
panic = 'abort'   # removes the need for this extra unwinding code.
strip = "symbols"

[dev-dependencies]
# some test must be run sequentially. 
# if library is broken, alternative is: cargo test -- --test-threads 1
serial_test = "2.0.0"
