[package]
name = "karsher"
version = "0.5.0"
edition = "2021"
authors = ["Nordine Bittich"]
license = "MIT"
description = "karsher is a dumb cache written in rust"
homepage = "https://github.com/nbittich/karsher"
readme = "README.md"

[dependencies]
anyhow = "1.0.57"
dirs = "4.0.0"
hashbrown = { version = "0.12.1", features = ["serde"] }
lazy_static = "1.4.0"
nom = "7.1.1"
nu-ansi-term = "0.46.0"
rustyline = "9.1.2"
rustyline-derive = "0.6.0"
serde = {version = "1.0.137", features= ['serde_derive']}
serde_json = "1.0.81"
slab_tree = "0.3.2"
strum = { version = "0.24.0", features = ["derive", "strum_macros"] }


[profile.release]
opt-level = 's'  # Optimize for size.
lto = true # Link Time Optimization (LTO)
codegen-units = 1 # Set this to 1 to allow for maximum size reduction optimizations:
panic = 'abort' # removes the need for this extra unwinding code.