[package]
name = "karsher"
version = "0.2.0"
edition = "2021"
authors = ["Nordine Bittich"]
license = "MIT"
description = "karsher is a dumb cache written in rust"
homepage = "https://github.com/nbittich/karsher"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
ctrlc = { version = "3.2.2", features = ["termination"] }
dirs = "4.0.0"
lazy_static = "1.4.0"
nom = "7.1.1"
serde = {version = "1.0.137", features= ['serde_derive']}
serde_json = "1.0.81"
