name: ci

on:
  push:
    branches:
      - 'master'
env:
  CARGO_TERM_COLOR: always
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl
      - name: Tests
        run: cargo test --verbose -- --nocapture
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nbittich/adana:latest
